#!/usr/bin/env python3

import os
import json
import time

input_params_path = os.environ['INPUT_PARAMS']
with open(input_params_path, 'r') as f:
    input_params = json.load(f)

sleep_sec = input_params['sleep_sec']

print(f"Start: nocontainer test. Sleeping for {sleep_sec} sec")
time.sleep(sleep_sec)
print("End: nocontainer test")